const readline = require('readline');
const http = require('http');
const path = require('path');
const fs = require('fs');

// Load environment variables manually
function loadEnv() {
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const key = match[1];
        let val = match[2] || '';
        if (val.startsWith('"') && val.endsWith('"')) {
          val = val.substring(1, val.length - 1);
        } else if (val.startsWith("'") && val.endsWith("'")) {
          val = val.substring(1, val.length - 1);
        }
        process.env[key] = val.trim();
      }
    }
  }
}
loadEnv();

const PORT = process.env.PORT || 3000;
const API_SECRET = process.env.API_SECRET || 'mindsync_secret_passphrase_2026';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

rl.on('line', (line) => {
  if (!line.trim()) return;
  try {
    const request = JSON.parse(line);
    handleRequest(request);
  } catch (err) {
    sendError(null, -32700, "Parse error");
  }
});

function sendResponse(id, result) {
  const response = {
    jsonrpc: "2.0",
    result: result,
    id: id
  };
  console.log(JSON.stringify(response));
}

function sendError(id, code, message, data = null) {
  const response = {
    jsonrpc: "2.0",
    error: {
      code: code,
      message: message,
      data: data
    },
    id: id
  };
  console.log(JSON.stringify(response));
}

// HTTP API request helper
function callServerAPI(method, endpoint, payload = null) {
  const postData = payload ? JSON.stringify(payload) : '';
  const options = {
    hostname: 'localhost',
    port: PORT,
    path: endpoint,
    method: method,
    headers: {
      'Authorization': `Bearer ${API_SECRET}`,
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(postData)
    }
  };

  return new Promise((resolve, reject) => {
    const req = http.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          try {
            resolve(JSON.parse(body));
          } catch (e) {
            resolve(body);
          }
        } else {
          reject(new Error(`Server status ${res.statusCode}: ${body}`));
        }
      });
    });
    req.on('error', reject);
    if (payload) req.write(postData);
    req.end();
  });
}

async function handleRequest(req) {
  const { method, params, id } = req;

  if (method === 'initialize') {
    return sendResponse(id, {
      protocolVersion: "2024-11-05",
      capabilities: {
        tools: {}
      },
      serverInfo: {
        name: "mindsync-mcp",
        version: "1.0.0"
      }
    });
  }

  if (method === 'tools/list') {
    return sendResponse(id, {
      tools: [
        {
          name: "mindsync_search",
          description: "Semantic search across the knowledge base",
          inputSchema: {
            type: "object",
            properties: {
              query: { type: "string", description: "Search query or statement" }
            },
            required: ["query"]
          }
        },
        {
          name: "mindsync_add_note",
          description: "Create a new note in MindSync and trigger Ingestion Agent processing",
          inputSchema: {
            type: "object",
            properties: {
              title: { type: "string", description: "Title of the note" },
              content: { type: "string", description: "Content body of the note" }
            },
            required: ["title", "content"]
          }
        },
        {
          name: "mindsync_clip_url",
          description: "Clip a URL article and ingest it into the second brain",
          inputSchema: {
            type: "object",
            properties: {
              url: { type: "string", description: "Valid HTTP or HTTPS web URL" }
            },
            required: ["url"]
          }
        },
        {
          name: "mindsync_list_tasks",
          description: "List all open and completed action item tasks",
          inputSchema: {
            type: "object",
            properties: {}
          }
        },
        {
          name: "mindsync_list_conflicts",
          description: "List unresolved factual contradictions identified in notes",
          inputSchema: {
            type: "object",
            properties: {}
          }
        },
        {
          name: "mindsync_list_sprouts",
          description: "List conceptual sprout ideas generated by the ideation loop",
          inputSchema: {
            type: "object",
            properties: {}
          }
        }
      ]
    });
  }

  if (method === 'tools/call') {
    const { name, arguments: args } = params;
    try {
      let resultText = '';

      if (name === 'mindsync_search') {
        const res = await callServerAPI('POST', '/api/search', { query: args.query });
        resultText = res.slice(0, 5).map(n => `[Note: ${n.title}]\nSummary: ${n.summary}\nSimilarity: ${(n.similarity*100).toFixed(0)}%`).join('\n\n');
      } else if (name === 'mindsync_add_note') {
        const res = await callServerAPI('POST', '/api/notes', { title: args.title, content: args.content });
        resultText = `Successfully created note: "${res.title}" with ID: ${res.id}`;
      } else if (name === 'mindsync_clip_url') {
        const res = await callServerAPI('POST', '/api/notes/clip', { url: args.url });
        resultText = `Successfully clipped URL. Ingested note "${res.title}" with ID: ${res.id}`;
      } else if (name === 'mindsync_list_tasks') {
        const res = await callServerAPI('GET', '/api/tasks');
        resultText = res.map(t => `- [${t.status === 'done' ? 'x' : ' '}] ${t.title} (Priority: ${t.priority.toUpperCase()})`).join('\n') || 'No tasks found.';
      } else if (name === 'mindsync_list_conflicts') {
        const res = await callServerAPI('GET', '/api/conflicts');
        resultText = res.map(c => `🔴 Conflict: ${c.description}\nSuggested Resolution: ${c.resolution}\nStatus: ${c.status.toUpperCase()}`).join('\n\n') || 'No conflicts found.';
      } else if (name === 'mindsync_list_sprouts') {
        const res = await callServerAPI('GET', '/api/sprouts');
        resultText = res.map(s => `💡 Sprout Idea: ${s.title}\nDescription: ${s.description}`).join('\n\n') || 'No sprouts found.';
      } else {
        return sendError(id, -32601, `Method not found: ${name}`);
      }

      return sendResponse(id, {
        content: [
          {
            type: "text",
            text: resultText
          }
        ]
      });

    } catch (err) {
      return sendError(id, -32000, `Execution error: ${err.message}`);
    }
  }

  // Handle other notifications / JSON RPC events
  if (id === undefined) return;
  return sendError(id, -32601, `Method not found: ${method}`);
}
